# Basic Site Settings
locale: "en-US"
remote_theme: "academicpages/academicpages.github.io"
plugins:
  - jekyll-remote-theme
title: "Katerina Capouskova"
title_separator: "-"
name: "Katerina Capouskova"
description: "Katerina's academic portfolio"
url: "https://katerinac.com"
baseurl: "" 
repository: "katerinac/katerinac.github.io"

# Navigation
nav: "main"

# Author Profile
author:
  name: "Katerina Capouskova"
  avatar: "/images/bio-photo.jpg" 
  bio: "Postdoctoral Researcher in Computational Neuroscience"
  location: "Lebanon, NH"
  employer: "Dartmouth College"
  uri: "https://katerinac.com"
  email: "kcapouskova@hotmail.com"
  googlescholar: "aFG8E_AjMZ4C"
  linkedin: "katerina-capouskova"
  github: "katerinac"
  orcid: "0000-0002-1247-943X"
  pubmed: "https://www.ncbi.nlm.nih.gov/pubmed/?term=katerina+capouskova"

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Reading Files
include:
  - .htaccess
  - _pages
  - _data
  - _includes
  - _publications
  - _talks
  - _teaching

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
